---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://cdt.hafas.de/opendata/apiserver/departureBoard?accessId={{accessId}}&lang=en&id={{stopId}}&format=json&maxJourneys=15&duration=1439
polling_headers: ''
polling_body: ''
id: 129030
custom_fields:
- keyname: authorBio
  name: About This Plugin
  field_type: author_bio
  description: This recipe can be used to show a timetable of a bus stop using the Mobiliteit.lu API.
  github_url: https://github.com/SourceDiver42/trmnl-mobiliteit
  email_address: sourcediver42@pm.me
- keyname: accessId
  field_type: string
  name: API Key
  description: API Key for the Mobiliteit API.
  help_text: Contact <a href="mailto:opendata-api@atp.etat.lu">opendata-api@atp.etat.lu</a> to get your personal API key.
- keyname: stopId
  field_type: string
  name: Stop ID
  description: Stop ID from the Mobiliteit API.
  help_text: The Stop ID can be found using the <a href="https://data.public.lu/en/datasets/api-mobiliteit-lu/" target="https://data.public.lu/en/datasets/api-mobiliteit-lu/" class="underline">guide</a> of the data.public.lu administration.
name: Mobiliteit.lu Checker
refresh_interval: 15
